language: python
script: pytest
python: 
  - "3.4"
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # some parts of the code below is taken from Keras. 
  # Ideally we'd like to set up the same test environment as there
  # so people can easy come over.
  -  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytest h5py
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install -e .[tests]